"""Initial migration

Revision ID: d27c55db27dc
Revises: 
Create Date: 2025-05-19 09:47:28.682329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'd27c55db27dc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=100), nullable=False),
                    sa.Column('description', sa.String(length=200), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('users',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('tg_id', sa.BigInteger(), nullable=False),
                    sa.Column('user_name', sa.String(length=100), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('user_name')
                    )
    op.create_table('sweet_items',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=100), nullable=False),
                    sa.Column('description', sa.String(length=200), nullable=False),
                    sa.Column('image_url', sa.String(length=200), nullable=False),
                    sa.Column('price', sa.Integer(), nullable=False),
                    sa.Column('category', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['category'], ['categories.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sweet_items')
    op.drop_table('users')
    op.drop_table('categories')
    # ### end Alembic commands ###
