"""SweetItem category to category_id

Revision ID: 64d3dab98509
Revises: 1481b1ea5a1b
Create Date: 2025-04-17 14:31:23.117397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64d3dab98509'
down_revision: Union[str, None] = '1481b1ea5a1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sweet_items', 'category_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sweet_items', sa.Column('category_id', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
