"""price float-int

Revision ID: 81d1c0e6226c
Revises: 64d3dab98509
Create Date: 2025-04-17 14:33:43.579711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81d1c0e6226c'
down_revision: Union[str, None] = '64d3dab98509'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sweet_items', 'price',
               existing_type=sa.FLOAT(),
               type_=sa.Integer(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sweet_items', 'price',
               existing_type=sa.Integer(),
               type_=sa.FLOAT(),
               existing_nullable=False)
    # ### end Alembic commands ###
